# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  NIX_PATH: /etc/nixos/configuration.nix

tasks:
  default:
    cmds:
      - echo "NixOS Configuration Tasks"
      - task -l
    silent: true
  switch:
    desc: nixos-rebuild switch flake
    cmds:
      - nixos-rebuild switch --flake .
  clean:
    desc: Cleans older nixos generations
    cmds:
      - nix-collect-garbage -d
